cache_dir: "{{ playbook_dir }}/cache"
bin_dir: "{{ cache_dir }}/bin"
homi_output_dir: "{{ cache_dir }}/homi-output"
klaytn_build_dir: "{{ cache_dir }}/klaytn-build"

klaytn_install_mode: package # package, build

klaytn_version: v1.0.3

# =======================
# for development or test
# =======================
klaytn_build_docker_base_image: "kaiachain/build_base:latest"
klaytn_build_docker_builder_image: "kaia_builder"
klaytn_build_local_git_dir:
klaytn_build_remote_git_url: "git@github.com:kaiachain/kaia.git"
klaytn_build_remote_git_branch: "dev"

klaytn_num_cn: 4
klaytn_num_pn: 4
klaytn_num_en: 1
klaytn_num_scn: 0
klaytn_num_spn: 0
klaytn_num_sen: 0

klaytn_network_name:
klaytn_network_id:
klaytn_chain_id:
klaytn_service_network_id:
klaytn_service_chain_id:

klaytn_custom_topology:

klaytn_bridge_enabled: 0

klaytn_port: 32323
klaytn_main_bridge_port: 50505
klaytn_sub_bridge_port: 50506
