---
- name: Create Network Topology
  klay_topology:
    num_cn: "{{ ctx.num_cn }}"
    num_pn: "{{ ctx.num_pn }}"
    num_en: "{{ ctx.num_en }}"
    use_default: True
    custom_topology: "{{ klaytn_custom_topology }}"
  register: topology_result
  when:
  - ctx.num_cn > 0 or ctx.num_pn > 0 or ctx.num_en > 0

- name: Get KNIs data for static-nodes.json
  klay_static_nodes:
    homi_output_dir: "{{ homi_output_dir }}"
    topology: "{{ topology_result.topology }}"
    is_service_chain: "{{ ctx.is_service_chain }}"
  register: static_nodes_result
  when:
  - ctx.num_cn > 0 or ctx.num_pn > 0 or ctx.num_en > 0

- name: Generate static-nodes.json
  copy:
    content: "{{ item.value['knis'] }}"
    dest: "{{ homi_output_dir }}/{{ item.value['node_type'] }}/scripts/static-nodes{{ item.value['node_num'] }}.json"
  with_dict: "{{ static_nodes_result['static_nodes'] }}"
  when:
  - ctx.num_cn > 0 or ctx.num_pn > 0 or ctx.num_en > 0