---
- name: Print default values
  debug:
    msg: "ansible_architecture={{ ansible_architecture }} ansible_default_ipv4={{ ansible_default_ipv4['address'] }} ansible_os_family={{ ansible_os_family }} ansible_system={{ ansible_system }}"

